# Site wide configuration

title: "David Newbury"
description:
logo: # 120x120 px default image used for Twitter summary card
teaser: # 400x250 px default teaser image used in image archive grid
locale:
url:


markdown: redcarpet

redcarpet:
  extensions: [ tables, strikethrough]



highlighter: pygments
timezone: America/New_York
sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
gems:
  - jekyll-sitemap


collections:
  my_work:
    output: true
    permalink: /work/:path/

# Site owner
owner:
  name: David Newbury
  email: 'david.newbury@gmail.com'
  twitter: 'workergnome'
  bio: 
  avatar: bio-photo.jpg # 160x160 px image for author byline

exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
